🐿 enhancement: accept API token + bash performance improvemence

diff --git a/src/cfupdater-dualstack b/src/cfupdater-dualstack
--- a/src/cfupdater-dualstack
+++ b/src/cfupdater-dualstack
@@ -27,39 +27,52 @@ ip6=$(curl -6 https://icanhazip.com/)
 # SCRIPT START
 echo "[Cloudflare DDNS] Check Initiated"
 
+# The execution of update
+if [[ ! -z "${auth_token}" ]]; then
+  header_auth_paramheader=( -H "Authorization: Bearer ${auth_token}" )
+else
+  header_auth_paramheader=( -H "X-Auth-Email: ${auth_email}" -H "X-Auth-Key: ${auth_key}" )
+fi
+
 # Seek for the record
-record4=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$zone_identifier/dns_records?name=$record_name&type=A" -H "X-Auth-Email: $auth_email" -H "X-Auth-Key: $auth_key" -H "Content-Type: application/json")
-record6=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$zone_identifier/dns_records?name=$record_name&type=AAAA" -H "X-Auth-Email: $auth_email" -H "X-Auth-Key: $auth_key" -H "Content-Type: application/json")
+seek_current_dns_value_cmd=( curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${zone_identifier}/dns_records?name=${record_name}&type=._._seek_dns_type_._." "${header_auth_paramheader[@]}" -H 'Content-Type: application/json' )
+record4="${seek_current_dns_value_cmd//._._seek_dns_type_._./A}"
+record6="${seek_current_dns_value_cmd//._._seek_dns_type_._./AAAA}"
 
 # Can't do anything without both record
-if [[ $record4 == *"\"count\":0"* || $record6 == *"\"count\":0"* ]]; then
+if [[ "${record4}" == *'"count":0'* || "${record6}" == *'"count\":0'* ]]; then
   >&2 echo -e "[Cloudflare DDNS] Dual stack records do not exist, perhaps create them first?"
   exit 1
 fi
 
 # Set existing IP address from the fetched record
-old_ip4=$(echo "$record4" | grep -Po '(?<="content":")[^"]*' | head -1)
-old_ip6=$(echo "$record6" | grep -Po '(?<="content":")[^"]*' | head -1)
+old_ip4=$(echo "${record4}" | sed 's/.*"content":"//;s/".*//')
+old_ip6=$(echo "${record6}" | sed 's/.*"content":"//;s/".*//')
 
 # Compare either one is the same
 # NOTE: The script will update even one IP remains the same.
-if [[ $ip4 == $old_ip4 && $ip6 == $old_ip6 ]]; then
+if [[ "${ip4}" == "${old_ip4}" && "${ip6}" == "${old_ip6}" ]]; then
   echo "[Cloudflare DDNS] IPs have not changed."
   exit 0
 fi
 
 # Set the record identifier from result
-record4_identifier=$(echo "$record4" | grep -Po '(?<="id":")[^"]*' | head -1)
-record6_identifier=$(echo "$record6" | grep -Po '(?<="id":")[^"]*' | head -1)
+record4_identifier=$(echo "${record4}" | sed 's/.*"id":"//;s/".*//')
+record6_identifier=$(echo "${record6}" | sed 's/.*"id":"//;s/".*//')
 
-# The execution of update
-update4=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$zone_identifier/dns_records/$record4_identifier" -H "X-Auth-Email: $auth_email" -H "X-Auth-Key: $auth_key" -H "Content-Type: application/json" --data "{\"id\":\"$zone_identifier\",\"type\":\"A\",\"proxied\":false,\"name\":\"$record_name\",\"content\":\"$ip4\",\"ttl\":120}")
-update6=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$zone_identifier/dns_records/$record6_identifier" -H "X-Auth-Email: $auth_email" -H "X-Auth-Key: $auth_key" -H "Content-Type: application/json" --data "{\"id\":\"$zone_identifier\",\"type\":\"AAAA\",\"proxied\":false,\"name\":\"$record_name\",\"content\":\"$ip6\",\"ttl\":120}")
+# The secret sause for executing the update
+json_data_v4='{"id":"'${zone_identifier}'","type":"A","proxied":false,"name":"'${record_name}'","content":"'${ip4}'","ttl":120}'
+json_data_v6='{"id":"'${zone_identifier}'","type":"AAAA","proxied":false,"name":"'${record_name}'","content":"'${ip6}'","ttl":120}'
+update_cmd=( curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/${zone_identifier}/dns_records/${record4_identifier}" "${header_auth_paramheader[@]}" -H 'Content-Type: application/json' )
+
+# Execution result
+update4="${update_cmd[@]}" --data "$json_data_v4"
+update6="${update_cmd[@]}" --data "$json_data_v6"
 
 # The moment of truth
-if [[ $update4 == *"\"success\":false"* || $update6 == *"\"success\":false"* ]]; then
-  >&2 echo -e "[Cloudflare DDNS] Update failed. DUMPING RESULTS:\n$update4\n$update6"
+if [[ "${update4}" == *'"success":false'* || "${update6}" == *'"success":false'* ]]; then
+  >&2 echo -e "[Cloudflare DDNS] Update failed for '${record4_identifier}' and '${record6_identifier}'.\n\nDUMPING RESULTS:\n${update4}\n\n${update6}"
   exit 1
 else
-  echo "[Cloudflare DDNS] IPv4 address '$ip4' and IPv6 address '$ip6' has been synced to Cloudflare."
+  echo "[Cloudflare DDNS] IPv4 address '${ip4}' and IPv6 address '${ip6}' has been synced to Cloudflare."
 fi
diff --git a/src/cfupdater-v4 b/src/cfupdater-v4
--- a/src/cfupdater-v4
+++ b/src/cfupdater-v4
@@ -26,35 +26,47 @@ ip=$(curl -4 https://icanhazip.com/)
 # SCRIPT START
 echo "[Cloudflare DDNS] Check Initiated"
 
+# The execution of update
+if [[ ! -z "${auth_token}" ]]; then
+  header_auth_paramheader=( -H "Authorization: Bearer ${auth_token}" )
+else
+  header_auth_paramheader=( -H "X-Auth-Email: ${auth_email}" -H "X-Auth-Key: ${auth_key}" )
+fi
+
 # Seek for the record
-record=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$zone_identifier/dns_records?name=$record_name" -H "X-Auth-Email: $auth_email" -H "X-Auth-Key: $auth_key" -H "Content-Type: application/json")
+seek_current_dns_value_cmd=( curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${zone_identifier}/dns_records?name=${record_name}&type=._._seek_dns_type_._." "${header_auth_paramheader[@]}" -H 'Content-Type: application/json' )
+record="${seek_current_dns_value_cmd//._._seek_dns_type_._./A}"
 
 # Can't do anything without the record
-if [[ $record == *"\"count\":0"* ]]; then
+if [[ "${record}" == *'"count":0'* ]]; then
   >&2 echo -e "[Cloudflare DDNS] Record does not exist, perhaps create one first?"
   exit 1
 fi
 
 # Set existing IP address from the fetched record
-old_ip=$(echo "$record" | grep -Po '(?<="content":")[^"]*' | head -1)
+old_ip=$(echo "${record}" | sed 's/.*"content":"//;s/".*//')
 
 # Compare if they're the same
-if [ $ip == $old_ip ]; then
+if [ "${ip}" == "${old_ip}" ]; then
   echo "[Cloudflare DDNS] IP has not changed."
   exit 0
 fi
 
 # Set the record identifier from result
-record_identifier=$(echo "$record" | grep -Po '(?<="id":")[^"]*' | head -1)
+record_identifier=$(echo "${record}" | sed 's/.*"id":"//;s/".*//')
 
-# The execution of update
-update=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$zone_identifier/dns_records/$record_identifier" -H "X-Auth-Email: $auth_email" -H "X-Auth-Key: $auth_key" -H "Content-Type: application/json" --data "{\"id\":\"$zone_identifier\",\"type\":\"A\",\"proxied\":false,\"name\":\"$record_name\",\"content\":\"$ip\",\"ttl\":120}")
+# The secret sause for executing the update
+json_data_v4='{"id":"'${zone_identifier}'","type":"A","proxied":false,"name":"'${record_name}'","content":"'${ip4}'","ttl":120}'
+update_cmd=( curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/${zone_identifier}/dns_records/${record4_identifier}" "${header_auth_paramheader[@]}" -H 'Content-Type: application/json' )
+
+# Execution result
+update="${update_cmd[@]}" --data "$json_data_v4"
 
 # The moment of truth
 case "$update" in
-*"\"success\":false"*)
-  >&2 echo -e "[Cloudflare DDNS] Update failed for $record_identifier. DUMPING RESULTS:\n$update"
+*'"success":false'*)
+  >&2 echo -e "[Cloudflare DDNS] Update failed for ${record_identifier}.\n\nDUMPING RESULTS:\n${update}"
   exit 1;;
 *)
-  echo "[Cloudflare DDNS] IPv4 context '$ip' has been synced to Cloudflare.";;
+  echo "[Cloudflare DDNS] IPv4 context '${ip}' has been synced to Cloudflare.";;
 esac
